version: "3.9"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "TestTestTest1"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "userOnboardingProject"
    volumes:
      - db-data:/postgresDB
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db-data: {}